import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ResponsiveAppBar from "@/app/components/ResponsiveAppBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveAppBar
            pages={[
              {label: "Tudo", link: "/"},
              {label: "Temporada", link: "/season"},
            ]}
        />
        {children}
      </body>
    </html>
  )
}
